## Tensorの基礎

In [1]:
# ライブラリ
import numpy as np
import torch

In [4]:
my_list = [1,2,3,4]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1, 2, 3, 4])

In [6]:
tensor_from_list.dtype

torch.int64

In [7]:
my_list = [1.,2.,3.,4.]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1., 2., 3., 4.])

In [8]:
tensor_from_list = torch.tensor(my_list, dtype=torch.float64)
tensor_from_list

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [12]:
zeros_tensor = torch.zeros((2, 3))
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.ones((3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [15]:
torch.rand(2, 2)

tensor([[0.8288, 0.5821],
        [0.0727, 0.5710]])

In [17]:
torch.rand(3, 3).dtype

torch.float32

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.random.rand(25)

array([0.90409498, 0.26514581, 0.00951622, 0.28150479, 0.83424564,
       0.75543772, 0.27386626, 0.7740845 , 0.3140399 , 0.58866699,
       0.21639093, 0.94674604, 0.12819278, 0.63655496, 0.58057643,
       0.91913029, 0.50566141, 0.19567966, 0.12681022, 0.77418549,
       0.992559  , 0.44181243, 0.97711495, 0.22666585, 0.69547179])

In [29]:
tensor_from_list.shape

torch.Size([4])

## 行列の演算

### 加減算, 要素ごとの乗除算

In [3]:
a = torch.rand((3, 3))
b = torch.rand((3, 3))

print(a)
print(b)

tensor([[0.6044, 0.6320, 0.4447],
        [0.6753, 0.3147, 0.1473],
        [0.9216, 0.0755, 0.4462]])


NameError: name 'pritn' is not defined

In [ ]:
a + b

In [4]:
a - b

tensor([[-0.0577,  0.1434, -0.3054],
        [ 0.2286,  0.0216,  0.0272],
        [ 0.5949, -0.8641, -0.4870]])

In [5]:
a * b

tensor([[0.4001, 0.3087, 0.3335],
        [0.3017, 0.0922, 0.0177],
        [0.3011, 0.0709, 0.4164]])

In [6]:
a / b

tensor([[0.9128, 1.2936, 0.5929],
        [1.5118, 1.0736, 1.2260],
        [2.8209, 0.0803, 0.4781]])

In [7]:
# 行列の積
torch.mm(a, b)

tensor([[0.8277, 0.8983, 0.9442],
        [0.6358, 0.5606, 0.6818],
        [0.7897, 0.8916, 1.1167]])

In [8]:
torch.matmul(a, b)

tensor([[0.8277, 0.8983, 0.9442],
        [0.6358, 0.5606, 0.6818],
        [0.7897, 0.8916, 1.1167]])

In [9]:
a @ b

tensor([[0.8277, 0.8983, 0.9442],
        [0.6358, 0.5606, 0.6818],
        [0.7897, 0.8916, 1.1167]])

### ブロードキャスティング

In [12]:
# (3, 3)のスカラー演算
a = torch.rand(3, 3)
scaler = 5
a + 5

tensor([[5.4692, 5.4504, 5.6012],
        [5.9318, 5.6982, 5.0899],
        [5.8280, 5.0785, 5.0658]])

In [13]:
a

tensor([[0.4692, 0.4504, 0.6012],
        [0.9318, 0.6982, 0.0899],
        [0.8280, 0.0785, 0.0658]])

In [15]:
b = torch.rand(1, 3)

In [16]:
b

tensor([[0.2234, 0.9339, 0.4424]])

In [17]:
a + b

tensor([[0.6926, 1.3842, 1.0437],
        [1.1552, 1.6321, 0.5323],
        [1.0513, 1.0124, 0.5082]])

In [19]:
a = torch.rand((32, 128,128, 3))
b = torch.rand((128, 128, 3))
# a + b

In [20]:
a = torch.rand((32, 128,128, 3))
b = torch.rand((128, 128, 6))
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 3

In [22]:

a = torch.rand((1, 128,128, 3))
b = torch.rand((8, 128, 128, 1))
# a + b

### 自動勾配

In [23]:
# テンサーを作成し、自動微分を有効にする
x = torch.ones(2, 2, requires_grad=True)

# テンサーに対する操作
y = x + 2
z = y*y*3
out = z.mean()

# 勾配を計算する
out.backward()

# 勾配 d(out)/dxを出力
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [40]:
# int型でもなくてもいい場合は、.(ドット)をつける
x = torch.tensor(2., requires_grad=True)
y = torch.tensor(3., requires_grad=True)
# w,
z = y * torch.log(x) + torch.sin(y)

# 勾配を計算する
z.backward()

# 勾配を出力する
print ('xの勾配', x.grad)
print('yの勾配',y.grad)


xの勾配 tensor(1.5000)
yの勾配 tensor(-0.2968)


In [29]:
torch.tensor(1)

tensor(1)

In [45]:
x.grad

tensor(1.5000)

In [53]:
# z = (x+ y)^2
x = torch.tensor(2., requires_grad=True)
y = torch.tensor(3., requires_grad=True)

# 中間ノードを求めるために、別の値に入れる
u = x + y

# 中間のノードに対する勾配を保持したい
u.retain_grad()

z = u ** 2
z.backward()

# xとyの勾配
print('xの勾配', x.grad)
print('yの勾配', y.grad)
print('x+yの勾配', u.grad)


xの勾配 tensor(10.)
yの勾配 tensor(10.)
x+yの勾配 None


/tmp/ipykernel_26/2860066900.py:17: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print('x+yの勾配', u.grad)


### with torch.no_grad()

In [57]:
x = torch.tensor(2., requires_grad=True)
y = torch.tensor(3., requires_grad=True)

with torch.no_grad():
    z1 = y * torch.log(x) + torch.sin(y)

z2 = y * torch.log(x) + torch.sin(y)

# z1.backward()
z2.backward()